### ISSUE TITLE
Make FXDesktopSearch accessible in a browser through webassembler

### ISSUE THREAD

**Issue by 3CE8D2BAC65BDD6AA9** [mirkosertic/FXDesktopSearch#23]
Very nice work.  I also notice that you are the creator of Bytecoder.  Is it possible to make FXDesktopSearch accessible in a broweser by compiling with your Bytecoder?  This will make desktop search much simpler.  Thanks!

**Comment by mirkosertic** [comment]
Thank you! Compiling FXDesktopSearch is a hard task for Bytecoder. Bytecoder yet is based on OpenJDK 10, but currently only supports the `java.base` package. Adding JavaFX on top of this would be a tought challenge.

**Comment by 3CE8D2BAC65BDD6AA9** [comment]
Thanks for the prompt reply and pointers.  For now, I am using sqlite3 FTS5 for full text search in a browser.  Hope some day can run Lucene in the browser!
