### ISSUE TITLE
[Suggestion] Combine offline and online search

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [mirkosertic/FXDesktopSearch#63]
Mix the results with the results of another search engine. So you can create a custom search engine in Chrome/Vivaldi/... with http://127.0.0.1:4711/search and always search in your own files aswell as the internet.

**Comment by mirkosertic** [comment]
Hi,
thank you for this proposal!
I guess this would be a greater enhancement. We'd need a set of browser plugins, at least for Firefox, plus a scraper for search results from DuckDuck or Google. Also we need to know how the two search results can be combined. Do you have an idea for this?
Regards,
Mirko

**Comment by mirkosertic** [comment]
Closed due to no further user feedback.
