### ISSUE TITLE
Status bar should show an ETA and percentage of how much FXDS has processed yet

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [mirkosertic/FXDesktopSearch#64]
You wrote

> You can see the indexing progress in the status bar of the application.

Yet there is no percentage in the status bar. All you see is it randomly popping up with filenames and occasionally the number of searched documents goes up in the search results. Apart from that, I never know when it's finished.

**Comment by mirkosertic** [comment]
Will be released with 3.2.0
