### ISSUE TITLE
Add tamil language support

### ISSUE THREAD

**Issue by prog20901** [mirkosertic/FXDesktopSearch#70]
sample TAMIL language PDF file you can download it from - http://www.messagehub.info/ta/messages.do and http://thefinish.in/download.html

**Comment by mirkosertic** [comment]
The download links are not working.

Yet I added Tamil to the list of supported languages. It was an easy one as FXDesktopSearch relies on https://github.com/optimaize/language-detector, which already supports Tamil.

**Comment by mirkosertic** [comment]
This change will be available in the next release.
