### ISSUE TITLE
incredibly slow

### ISSUE THREAD

**Issue by trevor122** [mirkosertic/FXDesktopSearch#83]
app is good but speed of indexing is incredibly slow

**Comment by mirkosertic** [comment]
Can you please post some quantitative metrics about the slowness? Also, is NLP processing enabled during indexing?

**Comment by prog20901** [comment]
i also faced similar issues when i index 1,500 text files of 300 kb each

**Comment by trevor122** [comment]
cca 1500 pdf and doc files, everything as default only I added my native language support, also I reminded that FXDesktop does not keep indexing status and after reboot starting indexing again from the start
 
 
 
martin
 
______________________________________________________________
> Od: "Mirko Sertic" <notifications@github.com>
> Komu: "mirkosertic/FXDesktopSearch" <FXDesktopSearch@noreply.github.com>
> Datum: 13.08.2019 08:47
> Předmět: Re: [mirkosertic/FXDesktopSearch] incredibly slow (#83)
>
Can you please post some quantitative metrics about the slowness? Also, is NLP processing enabled during indexing?

**Comment by mirkosertic** [comment]
Have you tried disabling entity extraction(NLP) in the options? This can become quite slow with large text corpus.

**Comment by mirkosertic** [comment]
Closed due to no further user feedback.
